GET https://bgopk8d83e.execute-api.eu-west-1.amazonaws.com/prod/spaces
###

POST https://1ertg407z7.execute-api.eu-west-1.amazonaws.com/prod/spaces
content-type: application/json

 {
    "location": "Dublin", 
    "name": "Best location"
 }
###

GET https://1ertg407z7.execute-api.eu-west-1.amazonaws.com/prod/spaces?id=343345

PUT https://1ertg407z7.execute-api.eu-west-1.amazonaws.com/prod/spaces?id=343345
content-type: application/json
{
    "name": "Best location 2"
}